### ISSUE TITLE
implement production-grade alerting for soroban-rpc

### ISSUE THREAD

**Issue by mollykarcher** [stellar/soroban-rpc#100]
Recently, the private RPC instance used by freighter was  failing on it's health endpoint, and there was no alerting that was triggered as a result. Note that this issue https://github.com/stellar/prometheus/issues/232 was already created to capture creating the alert for that specific critical alert.

However, we should also take a hollistic look at the alerting/monitoring for RPC, and (at a minimum):
- [ ] decide on a set of important/appropriate alerts. source feedback on this from the team and adjust as-needed
- [ ] set up a slack channel(s) to feed alerts into
    - [ ] up to your discretion is we should have separate channels for warnings vs critical (as we do for horizon), or if we want to feed warnings into slack at all
- [ ] alert the platform team [rota](https://portal.victorops.com/dash/stellar#/team/team-PrUkmi84BD3f9r1t/policies) in the case of critical alerts that need an on-calls attention
- [ ] document the process for adding alerts and link this somewhere in the platform survival guide

**Comment by 2opremio** [comment]
To start with, we want alerts when:
* RPC is unhealthy (i.e. getHealth endpoint indicates so)
* RAM/CPU usage is getting close to the limit (e.g. less than 30% leeway)
* Disk is running out (we will probably need this due to captive core regardless of the DB solution we end up using)
* Logged error rate is too high
* API endpoint error rate is too high
* RPC died
* Duration of requests is too high
* Requests are queuing up
* Ingestion is too slow
* Ingestion lags by more than 1 ledger

**Comment by 2opremio** [comment]
@sreuland ... and @stellar/platform-committers  in general. Do you have any other alert suggestions?

**Comment by mollykarcher** [comment]
This list sounds good to me! 

Some comments:
- `RPC died` sounds like the same thing as `RPC is unhealthy` to me, unless I'm misunderstanding it
- `Ingestion lags by more than 1 ledger`: this seems like it might be too low/too flappy. In general, RPC ingestion should be much faster than Horizon's so I'm not against us alerting sooner on it, but 1 ledger seems like it could potentially happen all the time. Every time core publishes a new ledger there's at least a small time period where we're working on ingesting and we're "behind"

**Comment by chowbao** [comment]
Would a request volume (too high/too low) alert be useful?

**Comment by 2opremio** [comment]
> Would a request volume (too high/too low) alert be useful?

Uhm, I am not sure how predictable the freighter requests are.

**Comment by psheth9** [comment]
Above list is pretty good, adding few more to brainstorm 

- Latency for critical endpoints (Alerts when some endpoints take more time to return response)
- Availability of service (i.e uptime - overlaps with `getHealth` endpoint)
- more specific alerts with respect to error rate (i.e 4xx/5xx)

I wonder if Ops team can come up with some common template/config here with respect to alerts related to resource utilization (i.e RAM/CPU/Disk usage etc) We will always need all these alerts when we setup a new service so why not  inherit the common config/template !!

**Comment by psheth9** [comment]
@mollykarcher Thinking a bit more about this, I feel like we should first figure out SLA/SLO first and then work on alerts. thoughts?

**Comment by sreuland** [comment]
> @sreuland ... and @stellar/platform-committers in general. Do you have any other alert suggestions?

may be worthwhile to capture a new metric `captive_core_restarts_total` and could alert on that, I think it provides more insight and would roll up to the other suggested `Ingestion lags by more than 1 ledger`

> RAM/CPU usage is getting close to the limit (e.g. less than 30% leeway)

would be interesting to know how an alert will know the `limit`, maybe it is just hardcoded as part of rule threshold applied on the raw ram/cpu metrics emitted, since the rpc process could be running on containerized environment, where ram/cpu capacities are sometimes reported based on the underlying host and not container specific.

do we also want to include in the criteria for these alerts that they are derivable from metrics emitted by rpc, i.e. none of the alerts should be dependent on metrics that may be emitted from container orchestration layers like k8s, this way the alerts can be reproducible in any deployment

**Comment by sreuland** [comment]
oops, didn't mean to click that close button

**Comment by 2opremio** [comment]
@psheth9 :

> * Latency for critical endpoints (Alerts when some endpoints take more time to return response)

Isn't this covered by:

 * Duration of requests is too high

?
 
> * Availability of service (i.e uptime - overlaps with `getHealth` endpoint)

I am not sure what would be the alert here.

> * more specific alerts with respect to error rate (i.e 4xx/5xx)

Isn't this covered by:

* API endpoint error rate is too high

?

(I agree that it would be good to report what error is causing it)

**Comment by 2opremio** [comment]
@sreuland :

> may be worthwhile to capture a new metric `captive_core_restarts_total` and could alert on that, I think it provides more insight and would roll up to the other suggested `Ingestion lags by more than 1 ledger`

I am not sure I understand. The lag could be caused by other things than captive core restarting (e.g. network problems, connectivity with other core instances, high CPU etc ...)

> would be interesting to know how an alert will know the `limit`, maybe it is just hardcoded as part of rule threshold applied

By limit I meant what's set in the k8s pod configuration.

**Comment by 2opremio** [comment]
I have started looking into how to implement the alerts.

It turns out that many are already there or should be there in a generic form (i.e. implemented identically for all pods, regardless of the specific containers running).

Check https://github.com/stellar/prometheus/blob/master/kube001-prd/ops.rules , it already provides things like `kube001-prd-pod-memory-limit`, `kube001-prd-k8s-namespace-cpu-quota-warning`.

Except for the following alerts (which are rpc-specific), I think the rest should be implemented in a generic way:

* Logged error rate is too high
* API endpoint error rate is too high
* Duration of requests is too high
* Requests are queuing up
* Ingestion is too slow
* Ingestion lags by more than 1 ledger

In fact, _Logged error rate is too high_ could probably be written in a generic way if we wanted to. Even the API alerts could probably be written generically for multiple services if we standarize the prometheus metrics.

@stellar/ops-team does the above make sense?

**Comment by 2opremio** [comment]
An issue with having generic alert notifications is alert exhaustion.

If we have generic alerts, it's going to be hard to notify them to an rpc-specific Slack channel. Having all alerts in the same channel is probably convenient for ops since they only need to look into a single place. However, if engineers are going to have first-line operational responsibility, this will likely cause exhaustion and alerts will fall through the cracks.

On the same topic, I have been looking in Slack for the expected CPU/memory alerts from RPC and I haven't been able to find them.

It could be that I am not able to find them or they simply didn't fire due to not reaching the 5m period.

**Comment by sreuland** [comment]
> I am not sure I understand. The lag could be caused by other things than captive core restarting (e.g. network problems, connectivity with other core instances, high CPU etc ...)

good point, that would likely justify capturing a new metric like `captive_core_restarts_total` as it could highlight a condition that is quite hard to detect otherwise from logs, etc.

**Comment by sreuland** [comment]
> By limit I meant what's set in the k8s pod configuration.

Ok, that touches on 'best practices' aspect of prod-grade alerting for rpc, so it may be replicatable regardless of how rpc was  deployed(k8s, docker-bare-metal, etc). Do we want to enable rpc to emit all compute metrics necessary for prod-grade alerting and then defer to [deploy your own rpc docs](https://developers.stellar.org/network/soroban-rpc/admin-guide#deploy-your-own-rpc-instance) to provide an example grafana dashboard that demonstrates the alerts with queries based solely on rpc's metrics, no reference to k8s metrics, and grafana substitution variables where users can override the thresholds?

If we don't want rpc to emit compute resource metrics of which accuracy can be challenging when on a virtual/container, we could provide a different example grafana dashboard in [deploy your own rpc docs](https://developers.stellar.org/network/soroban-rpc/admin-guide#deploy-your-own-rpc-instance) that demonstrates resource oriented alert rules with references to k8s metrics keys. for non-k8s rpc deployments where users are running the rpc image with docker-on-bare-metal or on a different container orchestration layer, we have to provide some alternate recommendation, or maybe not supported?
