### ISSUE TITLE
assess impact on RPC of upcoming protocol 21 changes

### ISSUE THREAD

**Issue by mollykarcher** [stellar/soroban-rpc#106]
For potential inclusion in protocol 21, the core team is working on a series of CAPs. We should look through these to identify if there is any significant downstream impact to RPC that it is possible to get ahead of, prior to the actual builds being available.

Improvements to host VM instantiation, which (at a minimum) has the potential to increase overall transaction volume on the network, as well as affect any RPC tests that assert on costs. Detail captured in the following CAPs:
- [CAP-54](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0054.md)
- [CAP-55](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0055.md)
- [CAP-56](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0056.md)

New host functions, details in the following CAPs:
- [CAP-51](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0051.md)
- [CAP-53](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0053.md)

XDR change not included in CAPs:
- https://github.com/stellar/stellar-xdr/pull/175

Output of this should be the implementation tickets for any work on our side that falls out of this

**Comment by 2opremio** [comment]
I don't think there is any considerable impact. We will have to

1. Update the XDR in stellar/go and update soroban-rpc accordingly (but I don't expect any unautomated code changes)
2. Update Core and rs-soroban-env/sdk. There _may_ be changes on how the VM is instantiated after the new cost model (@dmkozh can you confirm?), but ever since we moved the simulation code to rs-soroban-env I don't expect a high impact due to internal API changes.
3. Since the cost model changes, we should add a simulateTransaction (or rather `GetPreflight`) which exercises simulating transactions with the old cost model (to make sure we have no regressions)
4. I don't really expect any changes due to the new host functions (maybe the VM needs to be instantated differently just like we need for pnrg? @dmkozh can you confirm?). I am not even sure it's worth adding integration tests for the new functions.

**Comment by dmkozh** [comment]
> There may be changes on how the VM is instantiated after the new cost model (@dmkozh can you confirm?), b

There shouldn't be any non-test changes necessary. There could be changes in hardcoded expected instructions and resources fee  when you're testing with protocol 21 enabled.

> Since the cost model changes, we should add a simulateTransaction (or rather GetPreflight) which exercises simulating transactions with the old cost model (to make sure we have no regressions)

I'm not sure if this is something you can meaningfully test (there is an unbounded number of possible cost model configurations, so testing with any one of them is as good as testing with multiple). That said, what I think should be covered with tests is preflight both for protocol 20 and protocol 21 (or more generally protocol vCurr and protocol vNext). The reason is that there will be a period of time where a new version of RPC is being used, but the network hasn't been upgraded yet. That will cover structural changes in the cost model (as more cost types have been added).

> maybe the VM needs to be instantated differently just like we need for pnrg?

Not really, VM instantiation happens internally in the host code, so you just need to pick up a fresh env release to get it working. There are no changes in public API.

>  I am not even sure it's worth adding integration tests for the new functions.

I agree, I think 99% of the time RPC shouldn't worry about the new host functions.
